---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: roast
    tags.datadoghq.com/team: roast
    tags.datadoghq.com/version: 1.0.0
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
