---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: roast
    tags.datadoghq.com/team: roast
    tags.datadoghq.com/version: 1.0.0
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: roast
        tags.datadoghq.com/team: roast
        tags.datadoghq.com/version: 1.0.0
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:17.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-env
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
