name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore workloads (Aspire)
        run: dotnet workload restore

      - name: Restore & Build
        run: dotnet build -c Debug

      - name: Start AppHost
        run: dotnet run --project src/CoffeeTalk.AppHost/CoffeeTalk.AppHost.csproj &
        env:
          API_URL: ${{ secrets.API_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Install Aspire CLI
        run: dotnet tool install --global aspire.cli

      - name: Add dotnet tool cache to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Install Playwright browsers
        working-directory: tests/CoffeeTalk.E2E
        run: |
          dotnet build
          pwsh bin/Debug/net9.0/playwright.ps1 install --with-deps

      - name: Trigger E2E via Aspire CLI
        run: aspire run playwright --project src/CoffeeTalk.AppHost/CoffeeTalk.AppHost.csproj
